### ISSUE TITLE
Autoincrement

### ISSUE THREAD

**Issue by mothepro** [mothepro/University-Database#1]
`deptNO`, `positionID`, and `courseNO` are not auto increment columns.

Did you mean to make them as such?

**Comment by mothepro** [comment]
Found here
- [deptNO](https://github.com/mothepro/University-Database/blob/a7c8c9d93443bf9ffe9676aef2ac3fefaf2b2f13/config/schema.xml#L50)
- [positionID](https://github.com/mothepro/University-Database/blob/a7c8c9d93443bf9ffe9676aef2ac3fefaf2b2f13/config/schema.xml#L33)
- [courseNO](https://github.com/mothepro/University-Database/blob/a7c8c9d93443bf9ffe9676aef2ac3fefaf2b2f13/config/schema.xml#L76)

**Comment by zukeoh** [comment]
God get off my case. Maaaurice.

**Comment by mothepro** [comment]
:palm_tree:

**Comment by zukeoh** [comment]
You feeling sexy?!

**Comment by zukeoh** [comment]
Hey I just had a great idea.. You should follow up every Mo[insert project name] with Mo[insert project name]MoProblems.

**Comment by mothepro** [comment]
:laughing:
