### ISSUE TITLE
Unique Keys

### ISSUE THREAD

**Issue by mothepro** [mothepro/University-Database#2]
You need a new unique tag for each column because they are unique seperatley, not together.
- [Sample 1](https://github.com/mothepro/University-Database/blob/76e1207099d5a4e67f4179c68fbfa19dc8b23930/config/schema.xml#L61)
- [Sample 2](https://github.com/mothepro/University-Database/blob/76e1207099d5a4e67f4179c68fbfa19dc8b23930/config/schema.xml#L121)

**Comment by zukeoh** [comment]
I thought I could do one or more at a time like this..
<#unique [name="/IndexName/"]>
<#unique-column name="/ColumnName/" [size="/LengthOfIndexColumn/"] />
  ...
<#/unique>

Note: Had to add the # symbol to get it to show in chat here.

**Comment by mothepro** [comment]
Like this

```
<unique [name="/IndexName/"]>
  <unique-column name="/ColumnName/" [size="/LengthOfIndexColumn/"] />
  ...
</unique>
```

**Comment by zukeoh** [comment]
whet. how did you make it look like that?

**Comment by zukeoh** [comment]
```
<unique [name="/IndexName/"]>
    <unique-column name="/ColumnName/" [size="/LengthOfIndexColumn/"] />
    ...
</unique>
```

**Comment by zukeoh** [comment]
oh shit I'm gud

**Comment by mothepro** [comment]
Use the "`" symbol [Check this out](https://guides.github.com/features/mastering-markdown/)

---

But you have one

```
<unique [name="/IndexName/"]>
</unique>
```

for every unique index,
only add multiple columns if they are unique when they are together.

In our case it should be

```
<unique [name="/IndexName/"]>
  <unique-column name="/ColumnName/" [size="/LengthOfIndexColumn/"] />
</unique>
<unique [name="/AnotherIndexName/"]>
  <unique-column name="/AnotherColumnName/" [size="/LengthOfIndexColumn/"] />
</unique>

```

**Comment by zukeoh** [comment]
kill me

**Comment by zukeoh** [comment]
what does invalid label mean

**Comment by draas** [comment]
#invalidIssuesMatter

**Comment by zukeoh** [comment]
talk to me maaaurice.. I long to hear your chocolate voice

**Comment by mothepro** [comment]
:confounded: Because the code is INVALID

**Comment by zukeoh** [comment]
ok i take 6.9 hr nap while my sex monkey fixes it
